package Slide3;


import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;
public class JSliderDemo extends javax.swing.JFrame {
    public JSliderDemo() {
        initComponents();
        Hashtable data = new Hashtable();
        String [] sMonths= {"Jan","Feb","Mar","Apr","May","Jun","Jul","Aug",
            "Sep","Oct","Nov","Dec"};
        for(int i =0; i<12; i++){
          data.put(i, new JLabel(sMonths[i]));
        }
        sldThang.setLabelTable(data);
        
        // lay ngay thang nam hien tai set gia tri cho cac JSlider ngay, thang, nam
        Calendar can = Calendar.getInstance();
        sldNgay.setValue(can.get(Calendar.DAY_OF_MONTH));
        sldThang.setValue(can.get(Calendar.MONTH));
        sldNam.setValue(can.get(Calendar.YEAR));
        displayDate();
    }
    void displayDate(){
      SimpleDateFormat sdf = new SimpleDateFormat("EEE, dd - MMM - yyyy");
      int dd = sldNgay.getValue();
      int mm = sldThang.getValue();
      int yy = sldNam.getValue()-1900;
      Date d = new Date(yy, mm, dd);
      txtNgay.setText(sdf.format(d));
    }
    //..........
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sldNgay = new javax.swing.JSlider();
        sldThang = new javax.swing.JSlider();
        sldNam = new javax.swing.JSlider();
        txtNgay = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JSlider");

        sldNgay.setBackground(new java.awt.Color(255, 204, 204));
        sldNgay.setForeground(new java.awt.Color(0, 51, 51));
        sldNgay.setMajorTickSpacing(7);
        sldNgay.setMaximum(31);
        sldNgay.setMinimum(1);
        sldNgay.setMinorTickSpacing(1);
        sldNgay.setPaintLabels(true);
        sldNgay.setPaintTicks(true);
        sldNgay.setSnapToTicks(true);
        sldNgay.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldNgayStateChanged(evt);
            }
        });

        sldThang.setBackground(new java.awt.Color(153, 255, 153));
        sldThang.setMajorTickSpacing(3);
        sldThang.setMaximum(11);
        sldThang.setMinorTickSpacing(1);
        sldThang.setPaintLabels(true);
        sldThang.setPaintTicks(true);
        sldThang.setSnapToTicks(true);
        sldThang.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldThangStateChanged(evt);
            }
        });

        sldNam.setBackground(new java.awt.Color(255, 255, 102));
        sldNam.setMajorTickSpacing(5);
        sldNam.setMaximum(2030);
        sldNam.setMinimum(2000);
        sldNam.setMinorTickSpacing(1);
        sldNam.setPaintLabels(true);
        sldNam.setPaintTicks(true);
        sldNam.setSnapToTicks(true);
        sldNam.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldNamStateChanged(evt);
            }
        });

        txtNgay.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtNgay.setForeground(new java.awt.Color(255, 0, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sldNam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sldThang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sldNgay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sldNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(sldThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(sldNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldNgayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldNgayStateChanged
      displayDate();
    }//GEN-LAST:event_sldNgayStateChanged
    private void sldThangStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldThangStateChanged
      displayDate();
    }//GEN-LAST:event_sldThangStateChanged
    private void sldNamStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldNamStateChanged
      displayDate();
    }//GEN-LAST:event_sldNamStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JSliderDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider sldNam;
    private javax.swing.JSlider sldNgay;
    private javax.swing.JSlider sldThang;
    private javax.swing.JTextField txtNgay;
    // End of variables declaration//GEN-END:variables

}
