/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demobaovejava3;

import com.sun.corba.se.pept.transport.Connection;
import java.awt.List;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.ir.BreakNode;

/**
 *
 * @author dinh thang
 */
public class quanlysv extends javax.swing.JFrame {

    /**
     * Creates new form quanlysv
     */
    ArrayList<sinhvien> list = new ArrayList<>();
    int index =0;
     String url="jdbc:sqlserver://localhost;databaseName=demobaove";
        String username="sa";
        String password ="123";
    public quanlysv() {
        initComponents();
       loaddata();
        loadform(index);
       
    }
   
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        public void loaddata(){
            try {             
                 java.sql.Connection conn= DriverManager.getConnection(url,username,password);
                 String sql ="select * from sinhvien";
                 Statement st = conn.createStatement();
                 ResultSet rs = st.executeQuery(sql);
                
                 while(rs.next()){
                     
                     sinhvien sv = new sinhvien();
                     sv.setMasv(rs.getString("masv"));
                     sv.setTensv(rs.getString("Tensv")) ;
                     sv.setNgaysinh(rs.getDate("ngaysinh"));
                     sv.setSodt(rs.getString("sodt"));
                     sv.setGioiTinh(rs.getBoolean("gioitinh"));
                     sv.setDiachi(rs.getString("diachi")); 
                     list.add(sv);
                     // dưa dữ liệu từ database lên list
                 }
                 
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        // nhìn code tê code theo mà lỗi 
        
        public void loadform(int i){
           sinhvien sv = list.get(i);        
           txtmasv.setText(sv.getMasv());
           txthoten.setText(sv.getTensv());
           txtngaysinh.setText(sv.getNgaysinh()+"");
           txtsodt.setText(sv.getSodt());
           if(sv.isGioiTinh()==true){// bieesnm dạng boolen is
               rdonam.setSelected(true);
           }
           else{
               rdonu.setSelected(true);
           }
           txtdiachi.setText(sv.getDiachi());
            // dưa dữ liệu từ list lên form theo index
        }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        txtmasv = new javax.swing.JTextField();
        txtngaysinh = new javax.swing.JTextField();
        txtsodt = new javax.swing.JTextField();
        rdonam = new javax.swing.JRadioButton();
        rdonu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdiachi = new javax.swing.JTextArea();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndeleete = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnfist = new javax.swing.JButton();
        btnprev = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnlast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("mã sv:");

        jLabel2.setText("số dt:");

        jLabel3.setText("họ tên :");

        jLabel4.setText("ngày sinh :");

        jLabel5.setText("giới tính:");

        jLabel6.setText("địa chỉ:");

        buttonGroup1.add(rdonam);
        rdonam.setText("nam");

        buttonGroup1.add(rdonu);
        rdonu.setText("nữ");

        txtdiachi.setColumns(20);
        txtdiachi.setRows(5);
        jScrollPane1.setViewportView(txtdiachi);

        btnadd.setText("add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setText("update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndeleete.setText("xoa");
        btndeleete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleeteActionPerformed(evt);
            }
        });

        btnsave.setText("save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnfist.setText("<");
        btnfist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfistActionPerformed(evt);
            }
        });

        btnprev.setText("<<");
        btnprev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprevActionPerformed(evt);
            }
        });

        btnnext.setText(">>");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnlast.setText(">");
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtmasv)
                                    .addComponent(txthoten)
                                    .addComponent(txtngaysinh)
                                    .addComponent(txtsodt, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnadd)
                                    .addComponent(btnupdate)
                                    .addComponent(btndeleete)
                                    .addComponent(btnsave)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdonam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdonu))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnfist)
                        .addGap(28, 28, 28)
                        .addComponent(btnprev)
                        .addGap(30, 30, 30)
                        .addComponent(btnnext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnlast)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndeleete))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtsodt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsave))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdonam)
                    .addComponent(rdonu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfist)
                    .addComponent(btnprev)
                    .addComponent(btnnext)
                    .addComponent(btnlast))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleeteActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "ban muon xoa u ")==JOptionPane.OK_OPTION){
            
       
        try {
            java.sql.Connection conn = DriverManager.getConnection(url,username,password);
            String sql="delete sinhvien where MASV =?";
            PreparedStatement stp = conn.prepareStatement(sql);
            stp.setString(1, txtmasv.getText());
            stp.executeUpdate();
            JOptionPane.showMessageDialog(this, "xoas thanh cong");
        } catch (Exception e) {
            e.printStackTrace();
        } 
        }
    }//GEN-LAST:event_btndeleeteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        loaddata();
      
    }//GEN-LAST:event_formWindowOpened

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
 txtmasv.setText("");
 txthoten.setText("");
 txtdiachi.setText("");
 txtngaysinh.setText("");
 txtsodt.setText("");
 buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        try {
            java.sql.Connection conn = DriverManager.getConnection(url,username,password);
            String sql="update  sinhvien set Tensv=?,ngaysinh=?,sodt=?,gioitinh=?,diachi=? where MASV=?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, txthoten.getText());
            st.setString(2, txtngaysinh.getText());
            st.setString(3, txtsodt.getText());
           int i;
           if(rdonam.isSelected()){
               i=1;
           }
           else{
               i=0;
           }
           st.setInt(4,i);
           st.setString(5, txtdiachi.getText());
           st.setString(6, txtmasv.getText());
           st.executeUpdate();
           JOptionPane.showMessageDialog(this, "sua thanh cong");
           loaddata();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        int count=0;
        for(sinhvien x:list){
            if(txtmasv.getText().equals(x.masv)){
                JOptionPane.showMessageDialog(this, "khoong duoc trung massv");
                count++;
                break;
            }
                }
        if(txtmasv.getText().equals("")|| txthoten.getText().equals("")||txtdiachi.getText().equals("")||txtngaysinh.getText().equals("")||txtsodt.getText().equals(""))
        {
         JOptionPane.showMessageDialog(this,"khong duoc de trong mot truong nao");
         count++;
         
        }
        if(!rdonam.isSelected() && !rdonu.isSelected())
        {
            JOptionPane.showMessageDialog(this, "ban chua chon gioi tinh");
            count++;
        }
        if(count==0){
            
        
        try {
            java.sql.Connection conn = DriverManager.getConnection(url,username,password);   
            String sql ="insert into sinhvien values (?,?,?,?,?,?)";
            PreparedStatement st = conn.prepareStatement(sql);
            
            st.setString(1,txtmasv.getText());
            st.setString(2, txthoten.getText());
            st.setString(3, txtngaysinh.getText());
            st.setString(4, txtsodt.getText());
            int i ;
             if(rdonam.isSelected()){
                 i=1;               
             }
             else{
                 i=0;
             }
             st.setInt(5, i);
             st.setString(6, txtdiachi.getText());
             st.executeUpdate();
             JOptionPane.showMessageDialog(this, "them sinh vien thanh cong");
             conn.close();
             loaddata();
        } catch (Exception e) {
            e.printStackTrace();
        }
       
      }  
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnfistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfistActionPerformed
        // TODO add your handling code here:
        loadform(0);
    }//GEN-LAST:event_btnfistActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
        // TODO add your handling code here:
        loadform(list.size()-1);
    }//GEN-LAST:event_btnlastActionPerformed

    private void btnprevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprevActionPerformed
        // TODO add your handling code here:
       if (index == 0) {
            index = list.size() - 1;
            loadform(list.size() - 1);
        } else {
            index--;
            loadform(index);
       }
    }//GEN-LAST:event_btnprevActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
         if (index == list.size() - 1) {
            index = 0;
            loadform(index);
        } else {
            index++;
            loadform(index);
        }
    }//GEN-LAST:event_btnnextActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanlysv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanlysv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanlysv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlysv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanlysv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndeleete;
    private javax.swing.JButton btnfist;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprev;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdonam;
    private javax.swing.JRadioButton rdonu;
    private javax.swing.JTextArea txtdiachi;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtmasv;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtsodt;
    // End of variables declaration//GEN-END:variables
}
