package Slide4;



import javax.swing.*;
public class JListDemo2 extends javax.swing.JFrame {
    DefaultListModel modelSports, modelFavors;
    /** Creates new form JListDemo */
    public JListDemo2() {
        initComponents();
        String[]sports={"Bong da","Bong ro","Cau long","Tenis","Boi loi","Bong chuyen","Dua xe"};
        modelSports = new DefaultListModel();
        for (String item : sports) {
            modelSports.addElement(item);
        }
        lstSports.setModel(modelSports);

        modelFavors = new DefaultListModel();
        lstFavorites.setModel(modelFavors);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstSports = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstFavorites = new javax.swing.JList();
        btnRightAll = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        btnLeftAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JList Demo");

        lstSports.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lstSports.setForeground(new java.awt.Color(0, 0, 153));
        jScrollPane1.setViewportView(lstSports);

        lstFavorites.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lstFavorites.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane2.setViewportView(lstFavorites);

        btnRightAll.setText(">>>");
        btnRightAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightAllActionPerformed(evt);
            }
        });

        btnRight.setText(">> ");
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });

        btnLeft.setText("<< ");
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });

        btnLeftAll.setText("<<<");
        btnLeftAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRightAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLeftAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnRightAll)
                .addGap(18, 18, 18)
                .addComponent(btnRight)
                .addGap(18, 18, 18)
                .addComponent(btnLeft)
                .addGap(18, 18, 18)
                .addComponent(btnLeftAll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRightAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightAllActionPerformed
        //chuyen tat ca du lieu trong model sport => array sportItems
        Object[] sportItems = modelSports.toArray();

        //lay tat ca du lieu trong array sportItems => model Favorite
        for (Object item : sportItems) {
            modelFavors.addElement(item);
        }

        //xoa tat ca du lieu trong model sport
        modelSports.removeAllElements();
    }//GEN-LAST:event_btnRightAllActionPerformed

    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        if(lstFavorites.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Vui long chon 1 mon the thao bat ky !");
        }
        else{
            Object[] selectedItems =lstFavorites.getSelectedValues();
            for (Object item : selectedItems) {
                modelSports.addElement(item);
                modelFavors.removeElement(item);
            }
        }
    }//GEN-LAST:event_btnLeftActionPerformed

    private void btnLeftAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftAllActionPerformed
        // TODO add your handling code here:
         Object[] sportItems = modelFavors.toArray();

        //lay tat ca du lieu trong array sportItems => model Favorite
        for (Object item : sportItems) {
            modelSports.addElement(item);
        }

        //xoa tat ca du lieu trong model sport
        modelFavors.removeAllElements();
    }//GEN-LAST:event_btnLeftAllActionPerformed

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        // TODO add your handling code here:
        if(lstSports.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Vui long chon 1 mon the thao bat ky !");
        }
        else{
            Object[] selectedItems =lstSports.getSelectedValues();
            for (Object item : selectedItems) {
                modelFavors.addElement(item);
                modelSports.removeElement(item);
            }
        }
    }//GEN-LAST:event_btnRightActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JListDemo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnLeftAll;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnRightAll;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstFavorites;
    private javax.swing.JList lstSports;
    // End of variables declaration//GEN-END:variables

}
